/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: main_mtr_shared.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "main_mtr_shared.pb-c.h"
void   finger_status__init
                     (FingerStatus         *message)
{
  static const FingerStatus init_value = FINGER_STATUS__INIT;
  *message = init_value;
}
size_t finger_status__get_packed_size
                     (const FingerStatus *message)
{
  assert(message->base.descriptor == &finger_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t finger_status__pack
                     (const FingerStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &finger_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t finger_status__pack_to_buffer
                     (const FingerStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &finger_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FingerStatus *
       finger_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FingerStatus *)
     protobuf_c_message_unpack (&finger_status__descriptor,
                                allocator, len, data);
}
void   finger_status__free_unpacked
                     (FingerStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &finger_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor finger_status__field_descriptors[3] =
{
  {
    "positions",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(FingerStatus, positions),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speeds",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(FingerStatus, speeds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currents",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(FingerStatus, currents),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned finger_status__field_indices_by_name[] = {
  2,   /* field[2] = currents */
  0,   /* field[0] = positions */
  1,   /* field[1] = speeds */
};
static const ProtobufCIntRange finger_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor finger_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FingerStatus",
  "FingerStatus",
  "FingerStatus",
  "",
  sizeof(FingerStatus),
  3,
  finger_status__field_descriptors,
  finger_status__field_indices_by_name,
  1,  finger_status__number_ranges,
  (ProtobufCMessageInit) finger_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue finger_status_sample_rate__enum_values_by_number[13] =
{
  { "RATE_UNUSED", "FINGER_STATUS_SAMPLE_RATE__RATE_UNUSED", 0 },
  { "RATE_1MS", "FINGER_STATUS_SAMPLE_RATE__RATE_1MS", 1 },
  { "RATE_2MS", "FINGER_STATUS_SAMPLE_RATE__RATE_2MS", 2 },
  { "RATE_5MS", "FINGER_STATUS_SAMPLE_RATE__RATE_5MS", 5 },
  { "RATE_10MS", "FINGER_STATUS_SAMPLE_RATE__RATE_10MS", 10 },
  { "RATE_20MS", "FINGER_STATUS_SAMPLE_RATE__RATE_20MS", 20 },
  { "RATE_50MS", "FINGER_STATUS_SAMPLE_RATE__RATE_50MS", 50 },
  { "RATE_100MS", "FINGER_STATUS_SAMPLE_RATE__RATE_100MS", 100 },
  { "RATE_200MS", "FINGER_STATUS_SAMPLE_RATE__RATE_200MS", 200 },
  { "RATE_500MS", "FINGER_STATUS_SAMPLE_RATE__RATE_500MS", 500 },
  { "RATE_1000MS", "FINGER_STATUS_SAMPLE_RATE__RATE_1000MS", 1000 },
  { "UPON_EVENT", "FINGER_STATUS_SAMPLE_RATE__UPON_EVENT", 16382 },
  { "RATE_OFF", "FINGER_STATUS_SAMPLE_RATE__RATE_OFF", 16383 },
};
static const ProtobufCIntRange finger_status_sample_rate__value_ranges[] = {
{0, 0},{5, 3},{10, 4},{20, 5},{50, 6},{100, 7},{200, 8},{500, 9},{1000, 10},{16382, 11},{0, 13}
};
static const ProtobufCEnumValueIndex finger_status_sample_rate__enum_values_by_name[13] =
{
  { "RATE_1000MS", 10 },
  { "RATE_100MS", 7 },
  { "RATE_10MS", 4 },
  { "RATE_1MS", 1 },
  { "RATE_200MS", 8 },
  { "RATE_20MS", 5 },
  { "RATE_2MS", 2 },
  { "RATE_500MS", 9 },
  { "RATE_50MS", 6 },
  { "RATE_5MS", 3 },
  { "RATE_OFF", 12 },
  { "RATE_UNUSED", 0 },
  { "UPON_EVENT", 11 },
};
const ProtobufCEnumDescriptor finger_status_sample_rate__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "FingerStatusSampleRate",
  "FingerStatusSampleRate",
  "FingerStatusSampleRate",
  "",
  13,
  finger_status_sample_rate__enum_values_by_number,
  13,
  finger_status_sample_rate__enum_values_by_name,
  10,
  finger_status_sample_rate__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
