/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mtr_to_main.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mtr_to_main.pb-c.h"
void   mtr_feedback__init
                     (MtrFeedback         *message)
{
  static const MtrFeedback init_value = MTR_FEEDBACK__INIT;
  *message = init_value;
}
size_t mtr_feedback__get_packed_size
                     (const MtrFeedback *message)
{
  assert(message->base.descriptor == &mtr_feedback__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mtr_feedback__pack
                     (const MtrFeedback *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mtr_feedback__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mtr_feedback__pack_to_buffer
                     (const MtrFeedback *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mtr_feedback__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MtrFeedback *
       mtr_feedback__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MtrFeedback *)
     protobuf_c_message_unpack (&mtr_feedback__descriptor,
                                allocator, len, data);
}
void   mtr_feedback__free_unpacked
                     (MtrFeedback *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mtr_feedback__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   button_event__init
                     (ButtonEvent         *message)
{
  static const ButtonEvent init_value = BUTTON_EVENT__INIT;
  *message = init_value;
}
size_t button_event__get_packed_size
                     (const ButtonEvent *message)
{
  assert(message->base.descriptor == &button_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t button_event__pack
                     (const ButtonEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &button_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t button_event__pack_to_buffer
                     (const ButtonEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &button_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ButtonEvent *
       button_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ButtonEvent *)
     protobuf_c_message_unpack (&button_event__descriptor,
                                allocator, len, data);
}
void   button_event__free_unpacked
                     (ButtonEvent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &button_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bat_volt_resp__init
                     (BatVoltResp         *message)
{
  static const BatVoltResp init_value = BAT_VOLT_RESP__INIT;
  *message = init_value;
}
size_t bat_volt_resp__get_packed_size
                     (const BatVoltResp *message)
{
  assert(message->base.descriptor == &bat_volt_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bat_volt_resp__pack
                     (const BatVoltResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bat_volt_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bat_volt_resp__pack_to_buffer
                     (const BatVoltResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bat_volt_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BatVoltResp *
       bat_volt_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BatVoltResp *)
     protobuf_c_message_unpack (&bat_volt_resp__descriptor,
                                allocator, len, data);
}
void   bat_volt_resp__free_unpacked
                     (BatVoltResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bat_volt_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hand_type_resp__init
                     (HandTypeResp         *message)
{
  static const HandTypeResp init_value = HAND_TYPE_RESP__INIT;
  *message = init_value;
}
size_t hand_type_resp__get_packed_size
                     (const HandTypeResp *message)
{
  assert(message->base.descriptor == &hand_type_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hand_type_resp__pack
                     (const HandTypeResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hand_type_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hand_type_resp__pack_to_buffer
                     (const HandTypeResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hand_type_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HandTypeResp *
       hand_type_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HandTypeResp *)
     protobuf_c_message_unpack (&hand_type_resp__descriptor,
                                allocator, len, data);
}
void   hand_type_resp__free_unpacked
                     (HandTypeResp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hand_type_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   u__mtr_to_main__init
                     (UMtrToMain         *message)
{
  static const UMtrToMain init_value = U__MTR_TO_MAIN__INIT;
  *message = init_value;
}
size_t u__mtr_to_main__get_packed_size
                     (const UMtrToMain *message)
{
  assert(message->base.descriptor == &u__mtr_to_main__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t u__mtr_to_main__pack
                     (const UMtrToMain *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &u__mtr_to_main__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t u__mtr_to_main__pack_to_buffer
                     (const UMtrToMain *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &u__mtr_to_main__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UMtrToMain *
       u__mtr_to_main__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UMtrToMain *)
     protobuf_c_message_unpack (&u__mtr_to_main__descriptor,
                                allocator, len, data);
}
void   u__mtr_to_main__free_unpacked
                     (UMtrToMain *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &u__mtr_to_main__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mtr_feedback__field_descriptors[5] =
{
  {
    "current_finger_status",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MtrFeedback, n_current_finger_status),
    offsetof(MtrFeedback, current_finger_status),
    &finger_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq_num",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MtrFeedback, seq_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sample_rate",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MtrFeedback, sample_rate),
    &finger_status_sample_rate__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expected_finger_status",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(MtrFeedback, expected_finger_status),
    &finger_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fingers_locked",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(MtrFeedback, fingers_locked),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mtr_feedback__field_indices_by_name[] = {
  0,   /* field[0] = current_finger_status */
  3,   /* field[3] = expected_finger_status */
  4,   /* field[4] = fingers_locked */
  2,   /* field[2] = sample_rate */
  1,   /* field[1] = seq_num */
};
static const ProtobufCIntRange mtr_feedback__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor mtr_feedback__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MtrFeedback",
  "MtrFeedback",
  "MtrFeedback",
  "",
  sizeof(MtrFeedback),
  5,
  mtr_feedback__field_descriptors,
  mtr_feedback__field_indices_by_name,
  1,  mtr_feedback__number_ranges,
  (ProtobufCMessageInit) mtr_feedback__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue button_event__press_status__enum_values_by_number[3] =
{
  { "UNUSED", "BUTTON_EVENT__PRESS_STATUS__UNUSED", 0 },
  { "PRESSING", "BUTTON_EVENT__PRESS_STATUS__PRESSING", 1 },
  { "NOT_PRESSING", "BUTTON_EVENT__PRESS_STATUS__NOT_PRESSING", 2 },
};
static const ProtobufCIntRange button_event__press_status__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex button_event__press_status__enum_values_by_name[3] =
{
  { "NOT_PRESSING", 2 },
  { "PRESSING", 1 },
  { "UNUSED", 0 },
};
const ProtobufCEnumDescriptor button_event__press_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ButtonEvent.PressStatus",
  "PressStatus",
  "ButtonEvent__PressStatus",
  "",
  3,
  button_event__press_status__enum_values_by_number,
  3,
  button_event__press_status__enum_values_by_name,
  1,
  button_event__press_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor button_event__field_descriptors[2] =
{
  {
    "press_status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ButtonEvent, press_status),
    &button_event__press_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ButtonEvent, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned button_event__field_indices_by_name[] = {
  0,   /* field[0] = press_status */
  1,   /* field[1] = timestamp */
};
static const ProtobufCIntRange button_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor button_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ButtonEvent",
  "ButtonEvent",
  "ButtonEvent",
  "",
  sizeof(ButtonEvent),
  2,
  button_event__field_descriptors,
  button_event__field_indices_by_name,
  1,  button_event__number_ranges,
  (ProtobufCMessageInit) button_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bat_volt_resp__field_descriptors[1] =
{
  {
    "bat_volt",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BatVoltResp, bat_volt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bat_volt_resp__field_indices_by_name[] = {
  0,   /* field[0] = bat_volt */
};
static const ProtobufCIntRange bat_volt_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor bat_volt_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BatVoltResp",
  "BatVoltResp",
  "BatVoltResp",
  "",
  sizeof(BatVoltResp),
  1,
  bat_volt_resp__field_descriptors,
  bat_volt_resp__field_indices_by_name,
  1,  bat_volt_resp__number_ranges,
  (ProtobufCMessageInit) bat_volt_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hand_type_resp__field_descriptors[1] =
{
  {
    "hand_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(HandTypeResp, hand_type),
    &hand_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hand_type_resp__field_indices_by_name[] = {
  0,   /* field[0] = hand_type */
};
static const ProtobufCIntRange hand_type_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hand_type_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HandTypeResp",
  "HandTypeResp",
  "HandTypeResp",
  "",
  sizeof(HandTypeResp),
  1,
  hand_type_resp__field_descriptors,
  hand_type_resp__field_indices_by_name,
  1,  hand_type_resp__number_ranges,
  (ProtobufCMessageInit) hand_type_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor u__mtr_to_main__field_descriptors[4] =
{
  {
    "motor_feedback",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UMtrToMain, motor_feedback),
    &mtr_feedback__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "button_event",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UMtrToMain, button_event),
    &button_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bat_volt_resp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UMtrToMain, bat_volt_resp),
    &bat_volt_resp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hand_type_resp",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(UMtrToMain, hand_type_resp),
    &hand_type_resp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned u__mtr_to_main__field_indices_by_name[] = {
  2,   /* field[2] = bat_volt_resp */
  1,   /* field[1] = button_event */
  3,   /* field[3] = hand_type_resp */
  0,   /* field[0] = motor_feedback */
};
static const ProtobufCIntRange u__mtr_to_main__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor u__mtr_to_main__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "U_MtrToMain",
  "UMtrToMain",
  "UMtrToMain",
  "",
  sizeof(UMtrToMain),
  4,
  u__mtr_to_main__field_descriptors,
  u__mtr_to_main__field_indices_by_name,
  1,  u__mtr_to_main__number_ranges,
  (ProtobufCMessageInit) u__mtr_to_main__init,
  NULL,NULL,NULL    /* reserved[123] */
};
