/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: stark_common.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "stark_common.pb-c.h"
void   generic_req__init
                     (GenericReq         *message)
{
  static const GenericReq init_value = GENERIC_REQ__INIT;
  *message = init_value;
}
size_t generic_req__get_packed_size
                     (const GenericReq *message)
{
  assert(message->base.descriptor == &generic_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t generic_req__pack
                     (const GenericReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &generic_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t generic_req__pack_to_buffer
                     (const GenericReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &generic_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GenericReq *
       generic_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GenericReq *)
     protobuf_c_message_unpack (&generic_req__descriptor,
                                allocator, len, data);
}
void   generic_req__free_unpacked
                     (GenericReq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &generic_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor generic_req__field_descriptors[1] =
{
  {
    "req",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(GenericReq, req),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned generic_req__field_indices_by_name[] = {
  0,   /* field[0] = req */
};
static const ProtobufCIntRange generic_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor generic_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GenericReq",
  "GenericReq",
  "GenericReq",
  "",
  sizeof(GenericReq),
  1,
  generic_req__field_descriptors,
  generic_req__field_indices_by_name,
  1,  generic_req__number_ranges,
  (ProtobufCMessageInit) generic_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue led_mode__enum_values_by_number[7] =
{
  { "LED_MODE_UNUSED", "LED_MODE__LED_MODE_UNUSED", 0 },
  { "LED_MODE_SHUTDOWN", "LED_MODE__LED_MODE_SHUTDOWN", 1 },
  { "LED_MODE_KEEP", "LED_MODE__LED_MODE_KEEP", 2 },
  { "LED_MODE_BLINK", "LED_MODE__LED_MODE_BLINK", 3 },
  { "LED_MODE_ONE_SHOT", "LED_MODE__LED_MODE_ONE_SHOT", 4 },
  { "LED_MODE_BLINK0_5HZ", "LED_MODE__LED_MODE_BLINK0_5HZ", 5 },
  { "LED_MODE_BLINK2HZ", "LED_MODE__LED_MODE_BLINK2HZ", 6 },
};
static const ProtobufCIntRange led_mode__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex led_mode__enum_values_by_name[7] =
{
  { "LED_MODE_BLINK", 3 },
  { "LED_MODE_BLINK0_5HZ", 5 },
  { "LED_MODE_BLINK2HZ", 6 },
  { "LED_MODE_KEEP", 2 },
  { "LED_MODE_ONE_SHOT", 4 },
  { "LED_MODE_SHUTDOWN", 1 },
  { "LED_MODE_UNUSED", 0 },
};
const ProtobufCEnumDescriptor led_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "LedMode",
  "LedMode",
  "LedMode",
  "",
  7,
  led_mode__enum_values_by_number,
  7,
  led_mode__enum_values_by_name,
  1,
  led_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue led_color__enum_values_by_number[8] =
{
  { "LED_COLOR_UNCHANGED", "LED_COLOR__LED_COLOR_UNCHANGED", 0 },
  { "LED_COLOR_R", "LED_COLOR__LED_COLOR_R", 1 },
  { "LED_COLOR_G", "LED_COLOR__LED_COLOR_G", 2 },
  { "LED_COLOR_RG", "LED_COLOR__LED_COLOR_RG", 3 },
  { "LED_COLOR_B", "LED_COLOR__LED_COLOR_B", 4 },
  { "LED_COLOR_RB", "LED_COLOR__LED_COLOR_RB", 5 },
  { "LED_COLOR_GB", "LED_COLOR__LED_COLOR_GB", 6 },
  { "LED_COLOR_RGB", "LED_COLOR__LED_COLOR_RGB", 7 },
};
static const ProtobufCIntRange led_color__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex led_color__enum_values_by_name[8] =
{
  { "LED_COLOR_B", 4 },
  { "LED_COLOR_G", 2 },
  { "LED_COLOR_GB", 6 },
  { "LED_COLOR_R", 1 },
  { "LED_COLOR_RB", 5 },
  { "LED_COLOR_RG", 3 },
  { "LED_COLOR_RGB", 7 },
  { "LED_COLOR_UNCHANGED", 0 },
};
const ProtobufCEnumDescriptor led_color__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "LedColor",
  "LedColor",
  "LedColor",
  "",
  8,
  led_color__enum_values_by_number,
  8,
  led_color__enum_values_by_name,
  1,
  led_color__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue hand_type__enum_values_by_number[5] =
{
  { "HANDTYPE_UNUSED", "HAND_TYPE__HANDTYPE_UNUSED", 0 },
  { "REGULAR_RIGHT", "HAND_TYPE__REGULAR_RIGHT", 1 },
  { "REGULAR_LEFT", "HAND_TYPE__REGULAR_LEFT", 2 },
  { "MINI_RIGHT", "HAND_TYPE__MINI_RIGHT", 3 },
  { "MINI_LEFT", "HAND_TYPE__MINI_LEFT", 4 },
};
static const ProtobufCIntRange hand_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex hand_type__enum_values_by_name[5] =
{
  { "HANDTYPE_UNUSED", 0 },
  { "MINI_LEFT", 4 },
  { "MINI_RIGHT", 3 },
  { "REGULAR_LEFT", 2 },
  { "REGULAR_RIGHT", 1 },
};
const ProtobufCEnumDescriptor hand_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "HandType",
  "HandType",
  "HandType",
  "",
  5,
  hand_type__enum_values_by_number,
  5,
  hand_type__enum_values_by_name,
  1,
  hand_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue finger_id__enum_values_by_number[7] =
{
  { "FINGERID_UNUSED", "FINGER_ID__FINGERID_UNUSED", 0 },
  { "FINGERID_THUMB", "FINGER_ID__FINGERID_THUMB", 1 },
  { "FINGERID_THUMB_AUX", "FINGER_ID__FINGERID_THUMB_AUX", 2 },
  { "FINGERID_INDEX", "FINGER_ID__FINGERID_INDEX", 3 },
  { "FINGERID_MIDDLE", "FINGER_ID__FINGERID_MIDDLE", 4 },
  { "FINGERID_RING", "FINGER_ID__FINGERID_RING", 5 },
  { "FINGERID_PINKY", "FINGER_ID__FINGERID_PINKY", 6 },
};
static const ProtobufCIntRange finger_id__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex finger_id__enum_values_by_name[7] =
{
  { "FINGERID_INDEX", 3 },
  { "FINGERID_MIDDLE", 4 },
  { "FINGERID_PINKY", 6 },
  { "FINGERID_RING", 5 },
  { "FINGERID_THUMB", 1 },
  { "FINGERID_THUMB_AUX", 2 },
  { "FINGERID_UNUSED", 0 },
};
const ProtobufCEnumDescriptor finger_id__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "FingerId",
  "FingerId",
  "FingerId",
  "",
  7,
  finger_id__enum_values_by_number,
  7,
  finger_id__enum_values_by_name,
  1,
  finger_id__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
